# Generated by IBM TransformationAdvisor
# Sat Feb 19 01:22:49 UTC 2022

FROM maven:3.3-jdk-8 as builder
WORKDIR /git
COPY . /git
RUN mvn clean package

FROM ibmcom/websphere-traditional:8.5.5.17-ubi

# put app and scripts and properties in /work/config
# put external library (e.g db driver) in /work/config/lib
COPY --from=builder --chown=was:root /git/data/examples/modresorts-1.0.war /work/config/
COPY --chown=was:root ./src/config /work/config
COPY --chown=was:root ./lib /work/config/lib
RUN /work/configure.sh
